# Generated by Django 6.0.6 on 2026-06-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.SlugField(unique=True)),
                ('descripcion_ciudadano', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de gestión',
                'verbose_name_plural': 'Estados de gestión',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('SOLICITUD', 'Solicitud'), ('TRAMITE', 'Trámite')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(blank=True, help_text='Separar palabras clave con comas. Ej: poda, árbol, ramas, cables')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='citizen.area')),
            ],
            options={
                'verbose_name': 'Categoría de gestión',
                'verbose_name_plural': 'Categorías de gestión',
                'ordering': ['tipo', 'area__nombre', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('area_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizen.area')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizen.categoriagestion')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_ciudadanas', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizen.estadogestion')),
            ],
            options={
                'verbose_name': 'Gestión ciudadana',
                'verbose_name_plural': 'Gestiones ciudadanas',
                'ordering': ['-creada'],
            },
        ),
    ]
