# Generated by Django 6.0.6 on 2026-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagestion',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Mostrar en accesos rápidos'),
        ),
    ]
