# Generated by Django 6.0.6 on 2026-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_categoriagestion_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagestion',
            name='usos',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de usos'),
        ),
    ]
