# Generated by Django 6.0.6 on 2026-06-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_categoriagestion_usos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='gestiones/adjuntos/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento')], max_length=20)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='citizen.gestion')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
    ]
