# Generated by Django 6.0.6 on 2026-06-19 12:35

from django.db import migrations


def normalizar_estados(apps, schema_editor):
    EstadoGestion = apps.get_model("citizen", "EstadoGestion")
    Gestion = apps.get_model("citizen", "Gestion")

    estados = {
        "registrado": ("Iniciada", "Tu gestión fue recibida.", 1),
        "analisis": ("En análisis", "El área correspondiente está evaluando tu gestión.", 2),
        "programada": ("Programada", "La gestión fue programada para su intervención.", 3),
        "ejecucion": ("En ejecución", "La gestión se encuentra en ejecución.", 4),
        "finalizada": ("Finalizada", "La gestión fue finalizada.", 5),
        "rechazada": ("Rechazada", "La gestión fue rechazada o no corresponde.", 6),
        "reabierta": ("Reabierta", "La gestión fue reabierta para una nueva revisión.", 7),
    }

    equivalencias = {
        "pendiente": "registrado",
        "en-analisis": "analisis",
        "en-ejecucion": "ejecucion",
        "resuelto": "finalizada",
        "rechazado": "rechazada",
        "observado": "reabierta",
    }

    finales = {}

    for codigo, (nombre, descripcion, orden) in estados.items():
        estado, _ = EstadoGestion.objects.update_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "descripcion_ciudadano": descripcion,
                "orden": orden,
            },
        )
        finales[codigo] = estado

    for codigo_viejo, codigo_nuevo in equivalencias.items():
        try:
            viejo = EstadoGestion.objects.get(codigo=codigo_viejo)
        except EstadoGestion.DoesNotExist:
            continue

        nuevo = finales[codigo_nuevo]
        Gestion.objects.filter(estado=viejo).update(estado=nuevo)

        if viejo.id != nuevo.id:
            viejo.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_adjuntogestion'),
    ]

    operations = [
        migrations.RunPython(normalizar_estados, migrations.RunPython.noop),
    ]
