# Generated by Django 6.0.6 on 2026-06-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('REG', 'Registrada'), ('PEN', 'Pendiente de Asignar'), ('INP', 'En Curso'), ('COM', 'Finalizada')], default='REG', max_length=3, verbose_name='Estado')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Planificadas')),
                ('executed_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Ejecutadas')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('involved_persons', models.ManyToManyField(blank=True, related_name='involved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Personas Involucradas')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_resources', to='tasks.article', verbose_name='Artículo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Recurso de Tarea',
                'verbose_name_plural': 'Recursos de Tarea',
            },
        ),
    ]
