from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.citizen_login, name='citizen_login'),
    path('', views.home, name='citizen_home'),
    path('nueva-gestion/', views.nueva_gestion, name='citizen_nueva_gestion'),
    path('mis-gestiones/', views.mis_gestiones, name='citizen_mis_gestiones'),
    path('mis-reclamos/', views.mis_reclamos, name='citizen_mis_reclamos'),
    path('notificaciones/', views.notificaciones, name='citizen_notificaciones'),
    path("perfil/", views.mi_perfil, name="citizen_mi_perfil"),
    path('estado-servicios/', views.estado_servicios, name='citizen_estado_servicios'),
    path('mapa/', views.mapa_ciudadano, name='citizen_mapa'),
    path("api/categorias/buscar/", views.buscar_categorias, name="citizen_buscar_categorias"),
    path("reclamos/tipo/", views.reclamo_tipo, name="citizen_reclamo_tipo"),
    path("reclamos/detalle/<int:categoria_id>/", views.reclamo_detalle, name="citizen_reclamo_detalle"),
    path("reclamos/ubicacion/", views.reclamo_ubicacion, name="citizen_reclamo_ubicacion"),
    path("reclamos/evidencia/", views.reclamo_evidencia, name="citizen_reclamo_evidencia"),
    path("reclamos/resumen/", views.reclamo_resumen, name="citizen_reclamo_resumen"),
    path("reclamos/iniciado/<int:gestion_id>/", views.reclamo_iniciado, name="citizen_reclamo_iniciado"),
    path("mis-turnos/", views.mis_turnos, name="citizen_turnos"),
    path("reclamos/categorias/", views.reclamos_categorias, name="citizen_reclamos_categorias"),
    path("solicitudes/categorias/",views.solicitudes_categorias,name="citizen_solicitudes_categorias"),
    path("solicitudes/detalle/<int:categoria_id>/", views.solicitud_detalle, name="citizen_solicitud_detalle"),
    path("solicitudes/ubicacion/", views.solicitud_ubicacion, name="citizen_solicitud_ubicacion"),
    path("solicitudes/evidencia/", views.solicitud_evidencia, name="citizen_solicitud_evidencia"),
    path("solicitudes/resumen/", views.solicitud_resumen, name="citizen_solicitud_resumen"),
    path("solicitudes/iniciada/<int:gestion_id>/", views.solicitud_iniciada, name="citizen_solicitud_iniciada"),
    path("mis-solicitudes/", views.mis_solicitudes, name="citizen_mis_solicitudes"),
    path( "mis-gestiones/<int:gestion_id>/",views.gestion_detalle,name="citizen_gestion_detalle"),
    path("mis-gestiones/turno/<int:turno_id>/",views.turno_detalle,name="citizen_turno_detalle"),
    path("obtener-turno/", views.obtener_turno, name="citizen_obtener_turno"),
    path("mis-datos-turnero/", views.mis_datos_turnero, name="citizen_mis_datos_turnero"),
    path("confirmacion-turno/", views.confirmacion_turno, name="citizen_confirmacion_turno"),
]